# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: 'test'

# Pipeline:
stages:
  - install
  - build
  - deploy

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

Build_and_Test:
  stage: build
  before_script:
    - npm run clean
  script:
    - npm run compile:all

deploy_staging:
  image: ruby:latest
  only:
    - develop
  stage: deploy
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY
    - echo "Deployed to staging server"

deploy_production:
    image: ruby:latest
    only:
      - master
    stage: deploy
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
    script:
      - dpl --provider=heroku --app=$HEROKU_APP_NAME_PROD --api-key=$HEROKU_API_KEY
      - echo "Deployed to production server"